spring:
  application:
    name: moneyledger
  datasource:
    url: jdbc:postgresql://localhost:5432/moneyledger
    username: postgres
    password: qud$i@12
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"